In [1]:
import pandas as pd
import numpy as np

In [2]:
X = pd.read_csv('X_task.csv')
Y = pd.read_csv('Y_task.csv')
Z = pd.read_csv('Z_task.csv', index_col='index')

In [3]:
X

Х1    Х2    Х3    Х4
0  4.6  18.2  0.33  1.83
1  4.5  19.3  0.39  1.75
2  4.1  22.1  0.33  1.81
3  4.8  17.8  0.38  1.77
4  4.2  18.5  0.28  1.88
5  4.6  17.5  0.29  1.88
6  4.9  19.4  0.37  1.75

In [4]:
Y

Х1    Х2    Х3    Х4
0  4.1  18.5  0.45  1.81
1  3.9  16.3  0.35  1.75
2  4.2  19.4  0.41  1.64
3  3.8  15.4  0.36  1.67
4  4.2  16.3  0.38  1.79
5  4.4  18.2  0.37  1.68
6  3.9  17.4  0.47  1.75

In [5]:
Z

Х1    Х2    Х3    Х4
index                       
z1     4.5  19.2  0.39  1.82
z2     4.1  19.0  0.42  1.78

In [6]:
def get_cov_matrix(df):
    m = df.values
    cols = m.shape[1]
    cov_matrix = np.zeros((cols,cols), dtype=np.float32)
    
    for i in range(cols):
        for j in range(cols):
            p1 = m[:, i]
            p2 = m[:, j]
            cov_matrix[i,j] = np.mean((p1 - np.mean(p1))*(p2 - np.mean(p2)))
    
    return cov_matrix

np.set_printoptions(suppress=True)
np.set_printoptions(precision=2)

Sx = get_cov_matrix(X)
Sy = get_cov_matrix(Y)

print('Sx:')
print(Sx)

print('Sy:')
print(Sy)
    

Sx:
[[ 0.07 -0.22  0.01 -0.01]
 [-0.22  2.06  0.01 -0.02]
 [ 0.01  0.01  0.   -0.  ]
 [-0.01 -0.02 -0.    0.  ]]
Sy:
[[ 0.04  0.16 -0.   -0.  ]
 [ 0.16  1.75  0.03 -0.01]
 [-0.    0.03  0.    0.  ]
 [-0.   -0.01  0.    0.  ]]


In [7]:
S = 1/(len(X) + len(Y) - 2) * (len(X)*Sx + len(Y)*Sy)
print('S:')
print(S)

S:
[[ 0.07 -0.03  0.   -0.  ]
 [-0.03  2.22  0.02 -0.02]
 [ 0.    0.02  0.   -0.  ]
 [-0.   -0.02 -0.    0.  ]]


In [8]:
invS = np.linalg.inv(S)

np.set_printoptions(precision=5)
print('S⁻¹:')
print(invS)

S⁻¹:
[[ 18.69359   0.78162 -30.35858  22.91216]
 [  0.78162   0.55244  -6.35701   2.98406]
 [-30.35858  -6.35701 628.48804  40.8845 ]
 [ 22.91216   2.98406  40.8845  327.17673]]


In [9]:
A = invS@(np.mean(X, axis=0)-np.mean(Y, axis=0))
print('A:')
print(A)

A:
[ 13.52735   1.87778 -58.46194  39.94712]


In [10]:
Ux = X.values@A
Uy = Y.values@A

print('Ux:')
print(Ux)
print('Uy:')
print(Uy)

Ux:
[150.21223 144.22157 149.97297 146.84666 150.28508 153.23361 150.98953]
Uy:
[136.19752 132.81029 134.78772 125.98716 136.71252 139.17622 127.86042]


In [11]:
Ux_mean = np.mean(Ux)
Uy_mean = np.mean(Uy)
print('U̅x = ', Ux_mean)
print('U̅y = ', Uy_mean)

U̅x =  149.39452166444798
U̅y =  133.36169285179673


In [12]:
C = (Ux_mean + Uy_mean)/2
print('C =', C)

C = 141.37810725812236


In [13]:
strs = ['належить до першої (X) вибірки', 'належить до другої (Y) вибірки']

U = Z.values @ A
for i in range(len(U)):
    Uz = U[i]
    
    if Uz < C:
        if Ux_mean < C:
            print(f'Uz{i} = {Uz} < {C} - {strs[0]}' )
        else:
            print(f'Uz{i} = {Uz} < {C} - {strs[1]}' )
    else:
        if Ux_mean > C:
            print(f'Uz{i} = {Uz} > {C} - {strs[0]}' )
        else:
            print(f'Uz{i} = {Uz} > {C} - {strs[1]}' )
        
    
    

Uz0 = 146.83009068641644 > 141.37810725812236 - належить до першої (X) вибірки
Uz1 = 137.69185269356439 < 141.37810725812236 - належить до другої (Y) вибірки
